// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AzureTest.V1.Data.Models
{
    public partial class Uploads
    {
        public Guid Id { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string Extention { get; set; }
        public DateTime? UploadDate { get; set; }
    }
}